[project]
name = "haplosearch"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "django==2.2",
    "django-widget-tweaks==1.4.1",
    "prettyconf>=2.2.1",
]

[dependency-groups]
dev = [
    "ipython>=8.12.3",
    "pytest>=8.3.5",
]
prod = [
    "gunicorn>=23.0.0",
]
